### ISSUE TITLE
UVRA - Can it be used for reauthentication and not just bootstrapping?

### ISSUE THREAD

**Issue by sbweeden** [sbweeden/howtofido_site_feedback#1]
Originally from @christiaanbrand, and summarized here.

When user clicks "Try another way", UVRA is not shown but should be. This comes about because current doc recommendation is (perhaps ambiguously) to use UVRA for bootstrap only, and not reauthentication.

Ask is to add UVRA to "Try another way" workflow, with allowCredentials list populated with only the UVRA credentials of the current username.

**Comment by christiaanbrand** [comment]
Yes, a UVRA should totally be able to double-up as a way to re-auth if a
platform authenticator is not available. We should make that clear, Dirk.

**Comment by sbweeden** [comment]
@balfanz

**Comment by sbweeden** [comment]
I have updated the howtofido.securitypoc.com site to accept uvra for reauthentication.
