### ISSUE TITLE
Change Login with FIDO button

### ISSUE THREAD

**Issue by sbweeden** [sbweeden/howtofido_site_feedback#4]
Based on feedback from @balfanz and others, the current re-use of the Login with FIDO branded button for multiple use cases is confusing. A different approach is needed.

**Comment by sbweeden** [comment]
Idea is to change back to plain text buttons as was originally there, perhaps with some kind of "powered by FIDO" graphic nearby for marketing purposes.

**Comment by jasmsmit** [comment]
I think it's useful to keep the flashy, branded logo for the device credential login flow. The second-factor button should definitely be differentiated IMO

**Comment by jasmsmit** [comment]
As there are 3 locations (not just 2) where the branded button is currently used, we will update all buttons to be consistent.

**Comment by sbweeden** [comment]
Deployed new idea for branding thanks to @jasmsmit and closing this issue for now.
